#!/usr/bin/env bash

# exit on errors
set -e
# verbose output
set -x

# The following command will find all *.ipynb files (recursively) in the code directory
# and then pass them to the jupyter nbconvert command to execute and convert to html
# This could be changed to simply save an executed .ipynb file (--to notebook), 
# or other formats (markdown etc).
find . -name "ccf*.ipynb" -print0 | xargs -0 --verbose -I % --max-procs=$(nproc) \
jupyter nbconvert \
	--to html \
	--ExecutePreprocessor.allow_errors=True \
	--ExecutePreprocessor.timeout=-1 \
	--FilesWriter.build_directory=../results \
	--execute %
