environment_version: 1
credentials:
- type: aws
  id: KkVlXMtaIJqT22
  description: AIND
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: general
  id: GTQcxIKPIVX8BP
  description: DOTFILES_REPO
  value: CUSTOM_KEY
- type: api-key
  id: 2PuQeUT48mbWLB
  description: Codeocean API
  key: API_KEY
  secret: API_SECRET
