#!/usr/bin/env bash
set -e

if [ -n "$CUSTOM_KEY" ]; then
    printf "Installing dotfiles from $CUSTOM_KEY"
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/bin/ init $CUSTOM_KEY --apply
fi

# move VS code data directory into capsule, so it persists between cloud workstation runs
ln -s /root/capsule/code/.vscode/ /.vscode

# install updated version of code-server
VERSION=4.20.1
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xvz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -