#!/usr/bin/env bash
set -e

pip install -U --upgrade-strategy=only-if-needed \
git+https://github.com/scverse/spatialdata@v0.0.15 \
git+https://github.com/scverse/spatialdata-plot@v0.1.0

if [ -n "$CUSTOM_KEY" ]; then
    printf "Installing dotfiles via chezmoi, from $CUSTOM_KEY"
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/bin/ init $CUSTOM_KEY --apply
fi
ln -s /root/capsule/code/.vscode/ /.vscode

# VERSION=4.20.1
if [ -n "$CUSTOM_KEY_2" ]; then
    printf "Installing code-server version $CUSTOM_KEY_2"
    mkdir /.code-server
    cd /.code-server
    curl -fL "https://github.com/coder/code-server/releases/download/v$CUSTOM_KEY_2/code-server-$CUSTOM_KEY_2-linux-amd64.tar.gz" \
      | tar -xvz
    ln -s /.code-server/code-server-$CUSTOM_KEY_2-linux-amd64/bin/code-server  /usr/bin/code-server
    cd -
fi